// js/state.js
export function initState(){
  return {
	unitsPositions: {},
	rotateUnits: [],
	plannedMoves: {},
	noAnimation: false,
    mode: 'wait',
	_fovCache: {}, //w ui.js keszuje pole widzenia każdej kratki na mapie; za pierwszym razem rysuje i zapisuje tu
    round: 1,
    phase: 0,
    timer: 30,
    showCoords: false,
    showSectorIds: false,
    running: false,
    attackers: [],
    defenders: [],
    selected: null,
    flagCount: 0,
    over: false,
    winner: null,
    playerMoved: false,
    projectile: null,
    projectiles: [],
    highlightedUnit: null,
    highlightUntil: 0,
    movingUnits: {},
    processingTurn: false,
    cellToSector: new Map(),
    hoverCell: null,
    hoverFOV: null,
    flagPhase: 0,
    smoke: [],
    hitFlashes: {},
    ai: { objective: null, focusTarget: null, inertia: {} },
    attackersTarget: 5,
    defendersTarget: 4,
    planningHold: false,
    roundOverlayMs: 1500,
    turnPlans: { def: {}, att: {} },
    attackersHP: 2000,
    defendersHP: 1700,
  };
}